### ISSUE TITLE
QGIS 3.16 last working version

### ISSUE THREAD

**Issue by meyerlor** [gacarrillor/InvisibleLayersAndGroups#4]
Hello,

unfortunately the plugin is not working with the current QGIS versions (LTR 3.22 and 3.24). Projects created with older QGIS versions show some layers and hide others which were not set to be hidden.

Creating a new Project and trying to hide certain layers also won't work as it used to: grouping layers and hiding a layer in this group is leading to the whole group disapearing.

Having a sub-group and trying to hide it makes the very bottom layer disapear, although it is not in the (sub)-group.

Would love to see this great plugin work with the recent QGIS versions again! :)
![Hide_Groups](https://user-images.githubusercontent.com/15894401/159432847-776ea034-0296-4d92-a06e-96d6fef07096.gif)

**Comment by gacarrillor** [comment]
Hi, 

thanks for the report. Could you give this dev version a try?
If it's working well I could release it soon.



[InvisibleLayersAndGroups.zip](https://github.com/gacarrillor/InvisibleLayersAndGroups/files/8329304/InvisibleLayersAndGroups.zip)

**Comment by meyerlor** [comment]
Hey,

it is working like a charm - even old projects are now working again with this version and QGIS 3.24! 

Thanks for looking into this!

**Comment by gacarrillor** [comment]
Great!
Closing this issue because the solution will appear in v2.2
